<h1> Code for Lychee Yield Prediction </h1>

In [213]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.cm as cm
# multivariate linear regression with regularization
from sklearn.linear_model import LinearRegression, Ridge, Lasso
# support vector machine regression
from sklearn.svm import SVR
from sklearn.metrics import r2_score
# neural network
import tensorflow
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, GRU, Dense, Dropout, Bidirectional, BatchNormalization
# normalization
from sklearn.preprocessing import MinMaxScaler, StandardScaler
from sklearn.pipeline import Pipeline
# score
from sklearn.metrics import mean_absolute_error
from sklearn.model_selection import train_test_split, StratifiedShuffleSplit, GridSearchCV, RandomizedSearchCV
# import keras
import tensorflow.keras
from tensorflow.keras import optimizers, regularizers
# import regularizer
from tensorflow.keras.regularizers import l1, l2
# import matplotlib
import matplotlib.pyplot as plt
# os
import os

import pickle
from calendar import monthrange

In [214]:
def clean_text_to_number(df):
    '''
    convert all text to 0
    '''
    cols = df.columns
    type_list = []
    for col in cols:
        print(col)
        try:
            df[col].astype(float)
        except:
            for i in range(df[col].shape[0]):
                if isinstance(df[col].iloc[i], str):
                    df[col].iloc[i] = 0
    return df

In [215]:
# import data frame
rain_df     = pd.read_excel('rain_amount_2006-2019.xlsx')
humid_df    = pd.read_excel('relative_humid_2006-2019.xlsx')
temp_df     = pd.read_excel('temp_2006-2019.xlsx')
area_df     = pd.read_excel('area_1994-2018.xls', sheet_name = 'Sheet1')
lychee_yield_df = pd.read_excel('lycheeproduct.xlsx')

# extract data
rain_df     = rain_df.iloc[5:, :]
humid_df    = humid_df.iloc[5:, :]
temp_df     = temp_df.iloc[5:, :]

# reset index
rain_df     = rain_df.reset_index().drop(columns=['index'])
humid_df    = humid_df.reset_index().drop(columns=['index'])
temp_df     = temp_df.reset_index().drop(columns=['index'])

# set column name
rain_df.columns     = ['days', 'location', 'date', '1', '4', '7', '10', '13', '16', '19', '22', 'total']
humid_df.columns    = ['days', 'location', 'date', '1', '4', '7', '10', '13', '16', '19', '22', 'mean']
temp_df.columns     = ['days', 'location', 'date', '1', '4', '7', '10', '13', '16', '19', '22', 'mean']
lychee_yield_df.columns = ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', 'total', 'year']
area_df.columns     = ['year', 'district', 'code', 'province', 'allarea', 'yieldarea', 'yield', 'yieldperarea']
area_df['year']     = area_df['year'] - 543

# ดึงค่า date เก็บไว้ก่อน
all_datetime    = pd.to_datetime(rain_df['date'])

rain_df     = rain_df.drop(columns = ['location', 'days', 'date'])
humid_df    = humid_df.drop(columns =['location', 'days', 'date'])
temp_df     = temp_df.drop(columns =['location', 'days', 'date'])
area_df     = area_df.drop(columns = ['province'])

print('rain amount dataframe')
print(rain_df.shape)
print('humid dataframe')
print(humid_df.shape)
print('temperature dataframe')
print(temp_df.shape)
print('rain dataframe sample')
print(rain_df.head(5))
print('area dataframe sample')
print(area_df.head(5))

rain amount dataframe
(5051, 9)
humid dataframe
(5051, 9)
temperature dataframe
(5051, 9)
rain dataframe sample
   1  4  7 10 13 16 19 22 total
0  0  0  0  0  0  0  0  0     -
1  0  0  0  0  0  0  0  0     -
2  0  0  0  0  0  0  0  0     -
3  0  0  0  0  0  0  0  0     -
4  0  0  0  0  0  0  0  0     -
area dataframe sample
   year  district  code  allarea  yieldarea  yield  yieldperarea
0  1994         1    50    27127      22158  18856         851.0
1  1995         1    50    27470      23197  15078         650.0
2  1996         1    50    33049      24793  23281         939.0
3  1997         1    50    36736      26612  20385         766.0
4  1998         1    50    40725      27214   1769          65.0


In [216]:
# # get datetime from 3 hour data set
# all_year        = pd.DataFrame(all_datetime.dt.year)
# all_month       = pd.DataFrame(all_datetime.dt.month)
# all_day         = pd.DataFrame(all_datetime.dt.day)

# all_year.columns    = ['year']
# all_month.columns   = ['month']
# all_day.columns     = ['day']
# # concat to existing dataframe
# rain_df = pd.concat([all_year, all_month, all_day, rain_df], axis = 1)
# humid_df = pd.concat([all_year, all_month, all_day, humid_df], axis = 1)
# temp_df = pd.concat([all_year, all_month, all_day, temp_df], axis = 1)

# # clean text element and save in pickle form

# rain_df_clean = clean_text_to_number(rain_df)
# with open('rain_df_clean.pickle', 'wb') as f:
#     pickle.dump(rain_df_clean, f)
# humid_df_clean = clean_text_to_number(humid_df)
# with open('humid_df_clean.pickle', 'wb') as f:
#     pickle.dump(humid_df_clean, f)
# temp_df_clean = clean_text_to_number(temp_df)
# with open('temp_df_clean.pickle', 'wb') as f:
#     pickle.dump(temp_df_clean, f)

<h1> Load Data from pickle </h1> since clean dataframe take very long time. So after we clean it, we save dataframe in pickle form.

In [217]:
with open('rain_df_clean.pickle', 'rb') as f:
    rain_df_clean = pickle.load(f)
with open('humid_df_clean.pickle', 'rb') as f:
    humid_df_clean = pickle.load(f)
with open('temp_df_clean.pickle', 'rb') as f:
    temp_df_clean = pickle.load(f)

In [218]:
print(' --- rain amount dataframe sample ---')
print(rain_df_clean.tail(5))
print(' --- humid dataframe sample ---')
print(humid_df_clean.head(5))
print(' --- temperature dataframe sample ---')
print(temp_df_clean.head(5))
print(' --- area dataframe sample ---')
print(area_df.head(5))
print(' --- lychee yield dataframe sample ---')
print(lychee_yield_df.head(5))

--- rain amount dataframe sample ---
      year  month  day  1     4  7 10 13 16 19 22 total
5046  2019     10   26  0     0  0  0  0  0  0  0     0
5047  2019     10   27  0     0  0  0  0  0  0  0     0
5048  2019     10   28  0     0  0  0  0  0  0  0     0
5049  2019     10   29  0     0  0  0  0  0  0  0     0
5050  2019     10   30  4  11.5  0  0  0  0  0  0  15.5
 --- humid dataframe sample ---
   year  month  day   1   4   7  10  13  16  19  22 mean
0  2006      1    1  97  98  98  78  52  47  79  88   80
1  2006      1    2  97  99  99  76  52  48  82  91   81
2  2006      1    3  95  99  99  69  55  50  77  93   80
3  2006      1    4  97  99  99  70  52  49  80  91   80
4  2006      1    5  93  98  99  67  50  41  75  78   75
 --- temperature dataframe sample ---
   year  month  day     1     4     7    10    13    16    19    22  mean
0  2006      1    1  16.2  15.2  13.9  21.6  28.7  29.9  21.2  18.8  20.7
1  2006      1    2  16.9  15.8  14.6  22.8  28.5  29.1  20.6  17.6

In [219]:
def groupby_col(self, col):
    '''
    return 
        1 keys 
        2 dictionary of sub_df ที่ keys คือแต่ละ element ใน col name
    '''

    output_dic = {}
    all_ele = sorted(list(set(self[col])))

    for ele in all_ele:
        sub_df = self.loc[self[col] == ele, :]
        output_dic[ele] = sub_df

    return all_ele, output_dic

def groupby_mean(self, col):
    '''
    return 
        1 keys 
        2 dictionary of sub_df ที่ keys คือแต่ละ element ใน col name
    '''

    output_dic = {}
    all_ele = sorted(list(set(self[col])))
    for ele in all_ele:
        sub_df = self.loc[self[col] == ele, :].mean(axis=0)
        output_dic[ele] = sub_df
    
    return all_ele, output_dic

def groupby_max(self, col):
    '''
    return 
        1 keys 
        2 dictionary of sub_df ที่ keys คือแต่ละ element ใน col name
    '''

    output_dic = {}
    all_ele = sorted(list(set(self[col])))

    for ele in all_ele:
        sub_df = self.loc[self[col] == ele, :].max(axis = 0)
        output_dic[ele] = sub_df
    
    return all_ele, output_dic

def groupby_min(self, col):
    '''
    return 
        1 keys 
        2 dictionary of sub_df ที่ keys คือแต่ละ element ใน col name
    '''

    output_dic = {}
    all_ele = sorted(list(set(self[col])))

    for ele in all_ele:
        sub_df = self.loc[self[col] == ele, :].min(axis = 0)
        output_dic[ele] = sub_df
    
    return all_ele, output_dic

def groupby_sum(self, col):
    '''
    return 
        1 keys 
        2 dictionary of sub_df ที่ keys คือแต่ละ element ใน col name
    '''

    output_dic = {}
    all_ele = sorted(list(set(self[col])))

    for ele in all_ele:
        sub_df = self.loc[self[col] == ele, :].sum(axis = 0)
        output_dic[ele] = sub_df
    
    return all_ele, output_dic

# set method to class
setattr(pd.core.frame.DataFrame, 'groupby_col', groupby_col)
setattr(pd.core.frame.DataFrame, 'groupby_mean', groupby_mean)
setattr(pd.core.frame.DataFrame, 'groupby_sum', groupby_sum)
setattr(pd.core.frame.DataFrame, 'groupby_max', groupby_max)
setattr(pd.core.frame.DataFrame, 'groupby_min', groupby_min)

In [220]:
def export_output(filename, year_train, month_train, y_train_true, y_train_pred, year_test, month_test, y_test_true, y_test_pred):
    
    dic_train = {
        'year':year_train.reshape(-1),
        'month':month_train.reshape(-1),
        'y_true': y_train_true.reshape(-1),
        'y_pred': y_train_pred.reshape(-1)
    }

    dic_test = {
        'year':year_test.reshape(-1),
        'month':month_test.reshape(-1),
        'y_true': y_test_true.reshape(-1),
        'y_pred': y_test_pred.reshape(-1)
    }
    
    df_train = pd.DataFrame(dic_train)
    df_test = pd.DataFrame(dic_test)
    
    # Create a Pandas Excel writer using XlsxWriter as the engine.
    writer = pd.ExcelWriter(filename, engine='xlsxwriter')
    # Write centroids sheet
    df_train.to_excel(writer, sheet_name='train set')
    df_test.to_excel(writer, sheet_name='test set')
    # save output
    writer.save()


<h1> Rearrange for monthly data </h1>

In [221]:
## montly Temp 2006 - 2019
monthly_temp = np.array([1,1,1]).reshape(1,3)

all_year, sub_year_dic = temp_df_clean.groupby_col('year')

for year in all_year:
        all_month, sub_month_dic = sub_year_dic[year].groupby_mean('month')
        for month in all_month:
                # record year month and mean temp of each month
                daily_temp = np.array([year, month, sub_month_dic[month].iloc[-1]]).reshape(1,3)
                monthly_temp = np.append(monthly_temp, daily_temp, axis = 0)

monthly_temp = np.delete(monthly_temp, 0, axis = 0)
print(monthly_temp.shape)

(166, 3)


In [222]:
## montly Humid 2006 - 2019
monthly_humid = np.array([1,1,1]).reshape(1,3)

all_year, sub_year_dic = humid_df_clean.groupby_col('year')

for year in all_year:
        all_month, sub_month_dic = sub_year_dic[year].groupby_mean('month')

        for month in all_month:
                # record year month and mean temp of each month
                daily_humid = np.array([year, month, sub_month_dic[month].iloc[-1]]).reshape(1,3)
                monthly_humid = np.append(monthly_humid, daily_humid, axis = 0)

monthly_humid = np.delete(monthly_humid, 0, axis = 0)
print(monthly_humid.shape)

(166, 3)


In [223]:
## monthly Rain 2006 - 2019
monthly_rain = np.array([1,1,1]).reshape(1,3)

all_year, sub_year_dic = rain_df_clean.groupby_col('year')

for year in all_year:
        all_month, sub_month_dic = sub_year_dic[year].groupby_mean('month')

        for month in all_month:
                # record year month and mean temp of each month
                daily_rain = np.array([year, month, sub_month_dic[month].iloc[-1]]).reshape(1,3)
                monthly_rain = np.append(monthly_rain, daily_rain, axis = 0)

monthly_rain = np.delete(monthly_rain, 0, axis = 0)
print(monthly_rain.shape)

(166, 3)


In [224]:
## monthly Lychee yield 2004 - 2018
monthly_lychee = np.array([1,1,1]).reshape(1,3)

all_year, sub_year_dic = rain_df_clean.groupby_col('year')

for year in all_year:
        all_month, _ = sub_year_dic[year].groupby_mean('month')

        for month in all_month:
                # record year month and lychee yield of each month
                monthly_lychee_temp = lychee_yield_df.loc[lychee_yield_df['year']==year,:]
                if monthly_lychee_temp.size != 0:
                    monthly_yield = np.array([year, month, monthly_lychee_temp.iloc[0, month-1]]).reshape(1,3)
                    monthly_lychee = np.append(monthly_lychee, monthly_yield, axis = 0)

monthly_lychee = np.delete(monthly_lychee, 0, axis = 0)
print(monthly_lychee.shape)

(156, 3)


In [225]:
## monthly Lychee yield 2004 - 2018 but use yearly yield
monthly_lychee_yearlyyield = np.array([1,1,1]).reshape(1,3)

all_year, sub_year_dic = rain_df_clean.groupby_col('year')

for year in all_year:
        all_month, _ = sub_year_dic[year].groupby_mean('month')

        for month in all_month:
                # record year month and lychee yield of each month
                monthly_lychee_temp = lychee_yield_df.loc[lychee_yield_df['year']==year,:]
                if monthly_lychee_temp.size != 0:
                    monthly_yield = np.array([year, month, monthly_lychee_temp.iloc[0, -2]]).reshape(1,3)
                    monthly_lychee_yearlyyield = np.append(monthly_lychee_yearlyyield, monthly_yield, axis = 0)

monthly_lychee_yearlyyield = np.delete(monthly_lychee_yearlyyield, 0, axis = 0)
print(monthly_lychee_yearlyyield)

[[ 2006     1 24451]
 [ 2006     2 24451]
 [ 2006     3 24451]
 [ 2006     4 24451]
 [ 2006     5 24451]
 [ 2006     6 24451]
 [ 2006     7 24451]
 [ 2006     8 24451]
 [ 2006     9 24451]
 [ 2006    10 24451]
 [ 2006    11 24451]
 [ 2006    12 24451]
 [ 2007     1 23229]
 [ 2007     2 23229]
 [ 2007     3 23229]
 [ 2007     4 23229]
 [ 2007     5 23229]
 [ 2007     6 23229]
 [ 2007     7 23229]
 [ 2007     8 23229]
 [ 2007     9 23229]
 [ 2007    10 23229]
 [ 2007    11 23229]
 [ 2007    12 23229]
 [ 2008     1 19089]
 [ 2008     2 19089]
 [ 2008     3 19089]
 [ 2008     4 19089]
 [ 2008     5 19089]
 [ 2008     6 19089]
 [ 2008     7 19089]
 [ 2008     8 19089]
 [ 2008     9 19089]
 [ 2008    10 19089]
 [ 2008    11 19089]
 [ 2008    12 19089]
 [ 2009     1 27922]
 [ 2009     2 27922]
 [ 2009     3 27922]
 [ 2009     4 27922]
 [ 2009     5 27922]
 [ 2009     6 27922]
 [ 2009     7 27922]
 [ 2009     8 27922]
 [ 2009     9 27922]
 [ 2009    10 27922]
 [ 2009    11 27922]
 [ 2009    12

In [226]:
## monthly yield per area 2006 - 2018
monthly_area = np.array([1,1,1]).reshape(1,3)

all_year, _ = rain_df_clean.groupby_col('year')
for year in all_year:
        all_month, _ = sub_year_dic[year].groupby_mean('month')

        for month in all_month:
                # record year month and lychee yield of each month
                monthly_area_temp = area_df.loc[area_df['year']==year,:]
                if monthly_area_temp.size != 0:
                    monthly_area_temp = np.array([year, month, monthly_area_temp.iloc[0, -1]]).reshape(1,3)
                    monthly_area = np.append(monthly_area, monthly_area_temp, axis = 0)

monthly_area = np.delete(monthly_area, 0, axis = 0)
print(monthly_area.shape)

(156, 3)


In [227]:
## monthly all yield area 2006 - 2018
monthly_yieldarea = np.array([1,1,1]).reshape(1,3)

all_year, _ = rain_df_clean.groupby_col('year')

for year in all_year:
        all_month, _ = sub_year_dic[year].groupby_mean('month')

        for month in all_month:
                # record year month and lychee yield of each month
                monthly_area_temp = area_df.loc[area_df['year']==year,:]
                if monthly_area_temp.size != 0:
                    monthly_area_temp = np.array([year, month, monthly_area_temp.iloc[0, 4]]).reshape(1,3)
                    monthly_yieldarea = np.append(monthly_yieldarea, monthly_area_temp, axis = 0)

monthly_yieldarea = np.delete(monthly_yieldarea, 0, axis = 0)
print(monthly_area.shape)

(156, 3)


<h1> Rearrange for daily data </h1>

In [60]:
## daily Temp 2006 - 2019
daily_temp = np.array([1,1,1,1]).reshape(1,4)

# get yearly dic
all_year, sub_year_dic = temp_df_clean.groupby_col('year')

for year in all_year:
        # get monthly dic
        all_month, sub_month_dic = sub_year_dic[year].groupby_col('month')

        for month in all_month:
            # get daily dic
            all_day, sub_day_dic = sub_month_dic[month].groupby_mean('day')       

            for day in all_day:
                # get daily dataframe
                sub_day_df = sub_day_dic[day]
                daily_tempo = np.array([year, month, day, sub_day_df.iloc[-1]]).reshape(1,4)
                daily_temp = np.append(daily_temp, daily_tempo, axis = 0)

daily_temp = np.delete(daily_temp, 0, axis = 0)
print(daily_temp[:6, :])

In [61]:
## daily humid 2006 - 2019
daily_humid = np.array([1,1,1,1]).reshape(1,4)

# get yearly dic
all_year, sub_year_dic = humid_df_clean.groupby_col('year')

for year in all_year:
        # get monthly dic
        all_month, sub_month_dic = sub_year_dic[year].groupby_col('month')

        for month in all_month:
            # get daily dic
            all_day, sub_day_dic = sub_month_dic[month].groupby_mean('day')       

            for day in all_day:
                # get daily dataframe
                sub_day_df = sub_day_dic[day]
                daily_tempo = np.array([year, month, day, sub_day_df.iloc[-1]]).reshape(1,4)
                daily_humid = np.append(daily_humid, daily_tempo, axis = 0)

daily_humid = np.delete(daily_humid, 0, axis = 0)
print(daily_humid.shape)

In [62]:
## daily rain 2006 - 2019
daily_rain = np.array([1,1,1,1]).reshape(1,4)

# get yearly dic
all_year, sub_year_dic = rain_df_clean.groupby_col('year')

for year in all_year:
        # get monthly dic
        all_month, sub_month_dic = sub_year_dic[year].groupby_col('month')

        for month in all_month:
            # get daily dic
            all_day, sub_day_dic = sub_month_dic[month].groupby_mean('day')       

            for day in all_day:
                # get daily dataframe
                sub_day_df = sub_day_dic[day]
                daily_tempo = np.array([year, month, day, sub_day_df.iloc[-1]]).reshape(1,4)
                daily_rain = np.append(daily_rain, daily_tempo, axis = 0)

daily_rain = np.delete(daily_rain, 0, axis = 0)
print(daily_rain.shape)

In [63]:
## daily Lychee yield 2006 - 2018
daily_lychee = np.array([1,1,1,1]).reshape(1,4)

all_year, sub_year_dic = rain_df_clean.groupby_col('year')

for year in all_year:
        all_month, sub_month_dic = sub_year_dic[year].groupby_col('month')
        # record year month and lychee yield of each month
        daily_lychee_temp = lychee_yield_df.loc[lychee_yield_df['year']==year,:]

        for month in all_month:

                # get daily dic
                all_day, _ = sub_month_dic[month].groupby_mean('day')       

                for day in all_day:    

                    if daily_lychee_temp.size != 0:
                        # print(year, ' : ', month)
                        # print(daily_lychee_temp.iloc[0, month-1])
                        daily_yield = np.array([year, month, day, daily_lychee_temp.iloc[0, month-1]]).reshape(1,4)
                        daily_lychee = np.append(daily_lychee, daily_yield, axis = 0)

daily_lychee = np.delete(daily_lychee, 0, axis = 0)
print(daily_lychee[:6, :])

In [64]:
## daily Lychee yield 2006 - 2018 yearlyyield
daily_lychee_yearlyyield = np.array([1,1,1,1]).reshape(1,4)
all_year, sub_year_dic = rain_df_clean.groupby_col('year')

for year in all_year:
        all_month, sub_month_dic = sub_year_dic[year].groupby_col('month')
        # record year month and lychee yield of each month
        daily_lychee_temp = lychee_yield_df.loc[lychee_yield_df['year']==year,:]

        for month in all_month:

                # get daily dic
                all_day, _ = sub_month_dic[month].groupby_mean('day')       

                for day in all_day:    

                    if daily_lychee_temp.size != 0:
                        # print(year, ' : ', month)
                        # print(daily_lychee_temp.iloc[0, month-1])
                        daily_yield = np.array([year, month, day, daily_lychee_temp.iloc[0, -2]]).reshape(1,4)
                        daily_lychee_yearlyyield = np.append(daily_lychee_yearlyyield, daily_yield, axis = 0)

daily_lychee_yearlyyield = np.delete(daily_lychee_yearlyyield, 0, axis = 0)
print(daily_lychee_yearlyyield[:6, :])

In [65]:
## daily yield per area 2006 - 2018
daily_area = np.array([1,1,1,1]).reshape(1,4)

all_year, sub_year_dic = rain_df_clean.groupby_col('year')

for year in all_year:
        all_month, sub_month_dic = sub_year_dic[year].groupby_col('month')
        # record year month and lychee yield of each month
        area_temp = area_df.loc[area_df['year']==year,:]        

        for month in all_month:

                # get daily dic
                all_day, _ = sub_month_dic[month].groupby_mean('day')       

                for day in all_day:    

                    if area_temp.size != 0:
                        daily_area_temp = np.array([year, month, day, area_temp.iloc[0, -1]]).reshape(1,4)
                        daily_area = np.append(daily_area, daily_area_temp, axis = 0)

daily_area = np.delete(daily_area, 0, axis = 0)
print(daily_area.shape)

In [66]:
## daily yield per area 2006 - 2018
daily_yieldarea = np.array([1,1,1,1]).reshape(1,4)

all_year, sub_year_dic = rain_df_clean.groupby_col('year')

for year in all_year:
        all_month, sub_month_dic = sub_year_dic[year].groupby_col('month')
        # record year month and lychee yield of each month
        area_temp = area_df.loc[area_df['year']==year,:]        

        for month in all_month:

                # get daily dic
                all_day, _ = sub_month_dic[month].groupby_mean('day')       

                for day in all_day:    

                    if area_temp.size != 0:
                        daily_area_temp = np.array([year, month, day, area_temp.iloc[0, 4]]).reshape(1,4)
                        daily_yieldarea = np.append(daily_yieldarea, daily_area_temp, axis = 0)

daily_yieldarea = np.delete(daily_yieldarea, 0, axis = 0)
print(daily_yieldarea.shape)

<h1> Rearrange for 3-hourly data </h1>

In [18]:
## hourly Temp 2004 - 2019
threehourly_temp = np.array([1,1,1,1,1]).reshape(1,5)

# get yearly dic
all_year, sub_year_dic = temp_df_clean.groupby_col('year')

for year in all_year:
        # get monthly dic
        all_month, sub_month_dic = sub_year_dic[year].groupby_col('month')

        for month in all_month:
            # get daily dic
            all_day, sub_day_dic = sub_month_dic[month].groupby_col('day')       

            for day in all_day:
                # get daily dataframe
                sub_day_df = sub_day_dic[day]

                for hour in ['1', '4', '7', '10', '13', '16', '19', '22']:
                    threehourly_tempo = np.array([year, month, day, int(hour), sub_day_df[hour]]).reshape(1,5)
                    threehourly_temp = np.append(threehourly_temp, threehourly_tempo, axis = 0)

threehourly_temp = np.delete(threehourly_temp, 0, axis = 0)
print(threehourly_temp.shape)

In [19]:
## hourly Humid 2004 - 2019
threehourly_humid = np.array([1,1,1,1,1]).reshape(1,5)

# get yearly dic
all_year, sub_year_dic = humid_df_clean.groupby_col('year')

for year in all_year:
        # get monthly dic
        all_month, sub_month_dic = sub_year_dic[year].groupby_col('month')

        for month in all_month:
            # get daily dic
            all_day, sub_day_dic = sub_month_dic[month].groupby_col('day')       

            for day in all_day:
                # get daily dataframe
                sub_day_df = sub_day_dic[day]

                for hour in ['1', '4', '7', '10', '13', '16', '19', '22']:
                    threehourly_tempo = np.array([year, month, day, int(hour), sub_day_df[hour]]).reshape(1,5)
                    threehourly_humid = np.append(threehourly_humid, threehourly_tempo, axis = 0)

threehourly_humid = np.delete(threehourly_humid, 0, axis = 0)
print(threehourly_humid.shape)

In [33]:
## hourly Rain 2004 - 2019
threehourly_rain = np.array([1,1,1,1,1]).reshape(1,5)

# get yearly dic
all_year, sub_year_dic = rain_df_clean.groupby_col('year')

for year in all_year:
        # get monthly dic
        all_month, sub_month_dic = sub_year_dic[year].groupby_col('month')

        for month in all_month:
            # get daily dic
            all_day, sub_day_dic = sub_month_dic[month].groupby_col('day')       

            for day in all_day:
                # get daily dataframe
                sub_day_df = sub_day_dic[day]

                for hour in ['1', '4', '7', '10', '13', '16', '19', '22']:
                    threehourly_tempo = np.array([year, month, day, int(hour), sub_day_df[hour]]).reshape(1,5)
                    threehourly_rain = np.append(threehourly_rain, threehourly_tempo, axis = 0)

threehourly_rain = np.delete(threehourly_rain, 0, axis = 0)
print(threehourly_rain.shape)

In [26]:
## hourly Lychee yield 2004 - 2018
threehourly_lychee = np.array([1,1,1,1,1]).reshape(1,5)

all_year, sub_year_dic = rain_df_clean.groupby_col('year')

for year in all_year:
    all_month, sub_month_dic = sub_year_dic[year].groupby_col('month')
    monthly_lychee_temp = lychee_yield_df.loc[lychee_yield_df['year']==year,:]

    for month in all_month:
        # get daily dic
        all_day, _ = sub_month_dic[month].groupby_col('day')       

        for day in all_day:                
            for hour in ['1', '4', '7', '10', '13', '16', '19', '22']:
                if monthly_lychee_temp.size != 0:
                    threehourly_yield = np.array([year, month, day, int(hour), monthly_lychee_temp.iloc[0, month-1]]).reshape(1,5)
                    threehourly_lychee = np.append(threehourly_lychee, threehourly_yield, axis = 0)

threehourly_lychee = np.delete(threehourly_lychee, 0, axis = 0)
print(threehourly_lychee.shape)

In [ ]:
## hourly Lychee yield 2004 - 2018 yearlyyield
threehourly_lychee_lycheeyield = np.array([1,1,1,1,1]).reshape(1,5)

all_year, sub_year_dic = rain_df_clean.groupby_col('year')

for year in all_year:
    all_month, sub_month_dic = sub_year_dic[year].groupby_col('month')
    monthly_lychee_temp = lychee_yield_df.loc[lychee_yield_df['year']==year,:]

    for month in all_month:
        # get daily dic
        all_day, _ = sub_month_dic[month].groupby_col('day')       

        for day in all_day:                
            for hour in ['1', '4', '7', '10', '13', '16', '19', '22']:
                if monthly_lychee_temp.size != 0:
                    threehourly_yield = np.array([year, month, day, int(hour), monthly_lychee_temp.iloc[0, month-1]]).reshape(1,5)
                    threehourly_lychee_lycheeyield = np.append(threehourly_lychee_lycheeyield, threehourly_yield, axis = 0)

threehourly_lychee_lycheeyield = np.delete(threehourly_lychee_lycheeyield, 0, axis = 0)
print(threehourly_lychee_lycheeyield[:6,:])

In [38]:
## hourly yield per area 2004 - 2018
threehourly_area = np.array([1,1,1,1,1]).reshape(1,5)

all_year, sub_year_dic = rain_df_clean.groupby_col('year')

for year in all_year:
    all_month, sub_month_dic    = sub_year_dic[year].groupby_col('month')
    monthly_area_temp         = area_df.loc[area_df['year']==year,:]

    for month in all_month:
        # get daily dic
        all_day, _ = sub_month_dic[month].groupby_col('day')       

        for day in all_day:                
            for hour in ['1', '4', '7', '10', '13', '16', '19', '22']:
                if monthly_area_temp.size != 0:
                    threehourly_area_temp = np.array([year, month, day, int(hour), monthly_area_temp.iloc[0, -1]]).reshape(1,5)
                    threehourly_area = np.append(threehourly_area, threehourly_area_temp, axis = 0)

threehourly_area = np.delete(threehourly_area, 0, axis = 0)
print(threehourly_area.shape)

In [39]:
## hourly all area 2004 - 2018
threehourly_yieldarea = np.array([1,1,1,1,1]).reshape(1,5)

all_year, sub_year_dic = rain_df_clean.groupby_col('year')

for year in all_year:
    all_month, sub_month_dic    = sub_year_dic[year].groupby_col('month')
    monthly_area_temp           = area_df.loc[area_df['year']==year,:]

    for month in all_month:
        # get daily dic
        all_day, _ = sub_month_dic[month].groupby_col('day')       

        for day in all_day:                
            for hour in ['1', '4', '7', '10', '13', '16', '19', '22']:
                if monthly_area_temp.size != 0:
                    threehourly_area_temp = np.array([year, month, day, int(hour), monthly_area_temp.iloc[0, 4]]).reshape(1,5)
                    threehourly_yieldarea = np.append(threehourly_yieldarea, threehourly_area_temp, axis = 0)

threehourly_yieldarea = np.delete(threehourly_yieldarea, 0, axis = 0)
print(threehourly_yieldarea.shape)

Intersected
 year of all data is 2004 - 2018

<h1> Method for getting X data </h1>

In [228]:
def split_x_sequence(X, n_steps, ind_output):
    
    X_seq = np.ones((1, n_steps))

    for i in range(X.shape[0]):
        
        if i+n_steps > X.shape[0] - 1:
            break
        x_seq_temp = X[i:i+n_steps, ind_output].reshape(1,-1)
        X_seq = np.append(X_seq, x_seq_temp, axis = 0)
    
    return X_seq[1:,:]

def split_y_sequence(X, n_steps, ind_output, repeat):
    
    # repeat = False return only target
    # repeat = true return target with multiple row
    X_seq = np.ones((1, 1)) if repeat == False else np.ones((1, n_steps))

    for i in range(X.shape[0]):
        
        if i+n_steps > X.shape[0] - 1:
            break
        x_seq_temp = X[i+n_steps, ind_output].reshape(1, -1) if repeat == False else  X[i+n_steps, ind_output]*np.ones((1, n_steps))
        X_seq = np.append(X_seq, x_seq_temp, axis = 0)
    
    return X_seq[1:,:]

In [229]:
def get_XY_fr_resolution(df_list_input, df_list_output, n_steps, req_m_input = [1, 2], req_month = [4, 5, 6], axis = 1, yearlyyield = False):

    df_copy_list  = list()
    X             = list()

    # extract X
    count = 0
    for df, xy_split in df_list_input:
        df_copy = df.copy()
        ind_2004_2018 = np.logical_and(df_copy[:, 0] >= 2004, df_copy[:, 0] <= 2018)
        df_copy = df_copy[ind_2004_2018,:]

        # find index only for required input month
        if yearlyyield and count == 0:
            count = count + 1
            req_m_ind = np.zeros((df_copy.shape[0],))
            for i in req_m_input:
                req_m_ind = np.logical_or(req_m_ind, (df_copy[:,1] == i).reshape(-1,))

        df_copy = df_copy[req_m_ind, :]

        if xy_split == 'x':
            X_temp = split_x_sequence(df_copy, n_steps, -1)
            print('true')
            print(X_temp.shape)
        if xy_split == 'y':
            X_temp = split_y_sequence(df_copy, n_steps, -1, True) if axis == 2 else split_y_sequence(df_copy, n_steps, -1, False)
      
        X_temp = X_temp.reshape(X_temp.shape[0], X_temp.shape[1], 1)
        X.append(X_temp)

    # axis = 2 for rnn and axis = 1 for lr and svr
    X = np.concatenate(X, axis = axis)

    # extract y
    Y = split_y_sequence(df_list_output[0], n_steps, -1, False) if yearlyyield == False else split_y_sequence(df_list_output[0][req_m_ind, :], n_steps, -1, False)  

    # get only the data from required month
    all_year    = np.unique(df_copy[:, 0])
    all_month   = np.unique(df_copy[:, 1]) if yearlyyield == False else np.array([])
    req_ind     = np.zeros((X_temp.shape[0], 1))
    for year in all_year:
        for month in req_month:
            year_ind = df_copy[n_steps:, 0] == year
            
            if yearlyyield == False:
                month_ind = df_copy[n_steps:, 1] == month
                ym_ind = year_ind*month_ind
            else:
                ym_ind = year_ind

            ym_ind_where = np.where(ym_ind == 1)
            
            if len(ym_ind_where[0]) != 0:
                if yearlyyield == False:
                    # get only the data from required month only at the first index
                    first_ind = ym_ind_where[0][0]

                else:
                    # get only the data from the last index of each year
                    first_ind = ym_ind_where[0][0]                  

                ym_ind = np.zeros((ym_ind.shape[0], 1))
                
                try:
                    ym_ind[first_ind] = 1
                except:
                    pass

                ym_ind  = ym_ind.reshape(-1, 1)
                req_ind = req_ind + ym_ind

    req_ind = req_ind.astype(bool).reshape(-1)
    X = X[req_ind, :, :]
    Y = Y[req_ind]
    if axis == 1:
        X = X.reshape(X.shape[0], X.shape[1])
        Y = Y.reshape(Y.shape[0])

    n_features = X.shape[2] if axis == 2 else X.shape[1]
    n_size      = X.shape[0]

    year_target = df_copy[n_steps:, 0][req_ind]
    month_target = df_copy[n_steps:, 1][req_ind] if yearlyyield == False else np.array([])

    return X, Y, n_features, n_size, n_steps, year_target, month_target

In [230]:
def rmse(y_true, y_pred):

    ind_ignorezero = (y_true != 0).reshape(-1,)
    error = (y_true - y_pred)
    se = error**2
    mse = np.mean(se)
    rmse = mse**0.5
    return rmse

In [231]:
def mape(y_true, y_pred):
    error = y_true - y_pred
    pe     = (y_true - y_pred)/y_true*100
    ape = np.abs(pe)
    mape = np.mean(ape)

    return mape    

In [232]:
def mae(y_true, y_pred):

    error = y_true - y_pred
    ae = np.abs(error)
    mae = np.mean(ae)

    return mae

In [233]:
def r2(y_true, y_pred):
    y_mean  = np.mean(y_true)
    Stot    = np.sum((y_true - y_mean)**2)
    Sres    = np.sum((y_true - y_pred)**2)
    r_square    = 1 - Sres/Stot

    return r_square

Get y

<h1> Feature selection </h1>
Year (of the target), Month (of the target), Avg.Temp (3 and 4 month before), Avg.Humid (3 and 4 month before),
Rain amount (3 and 4 month before), lychee yield per area (1 year before), number of the day in target month,
lychee yield (of target month but 1 year before)

In [338]:
choose = 'monthly_yearlyyield'

if choose == 'monthly_yearlyyield_wyear':
    yearlyyield = True
    input_vec = [
        [monthly_temp, 'x'],
        # [monthly_humid, 'x'], 
        # [monthly_rain, 'x'], 
        # [monthly_area, 'x'], 
        # [monthly_yieldarea, 'x'], 
        # [monthly_lychee, 'x'],
        [monthly_yieldarea[:,0].reshape(-1,1), 'y']]   # target year

    output_vec = [monthly_lychee_yearlyyield]

if choose == 'monthly_yearlyyield_woyear':
    yearlyyield = True
    input_vec = [
        [monthly_temp, 'x'],
        # [monthly_humid, 'x'], 
        # [monthly_rain, 'x'], 
        # [monthly_area, 'x'], 
        # [monthly_yieldarea, 'x'], 
        # [monthly_lychee, 'x'],
        ]#[monthly_yieldarea[:,0].reshape(-1,1), 'y']]   # target year

    output_vec = [monthly_lychee_yearlyyield]
if choose == 'test':
    input_vec = [
        [daily_temp, 'x'], 
        [daily_yieldarea[:,0].reshape(-1,1), 'y'],   # target year
        [daily_yieldarea[:,0:2].reshape(-1,2), 'y']] # target month

    output_vec = [daily_lychee]

if choose == 'monthly':
    yearlyyield = False
    input_vec = [
        [monthly_temp, 'x'],
        # [monthly_humid, 'x'], 
        # [monthly_rain, 'x'], 
        # [monthly_area, 'x'], 
        [monthly_yieldarea, 'x'], 
        [monthly_lychee, 'x'], 
        [monthly_yieldarea[:,0].reshape(-1,1), 'y'],   # target year
        [monthly_yieldarea[:,0:2].reshape(-1,2), 'y']] # target month
    
    output_vec = [monthly_lychee]

if choose == 'daily':
    yearlyyield = False
    input_vec = [
        [daily_temp, 'x'],
        [daily_humid, 'x'], 
        # [daily_rain, 'x'], 
        # [daily_area, 'x'], 
        # [daily_yieldarea, 'x'], 
        [daily_lychee, 'x'], 
        [daily_yieldarea[:,0].reshape(-1,1), 'y'],   # target year
        [daily_yieldarea[:,0:2].reshape(-1,2), 'y']] # target month

    output_vec = [daily_lychee]

if choose == 'hourly':
    yearlyyield = False
    input_vec = [
        [hourly_temp, 'x'],
        # [hourly_humid, 'x'], 
        # [hourly_rain, 'x'], 
        # [hourly_area, 'x'], 
        [hourly_yieldarea, 'x'], 
        [hourly_lychee, 'x'], 
        [hourly_yieldarea[:,0].reshape(-1,1), 'y'],   # target year
        [hourly_yieldarea[:,0:2].reshape(-1,2), 'y']] # target month

    output_vec = [hourly_lychee]

# daily choose n_steps = 240
# hourly choose n_steps = 1920
# monthly choose n_steps = 4
# axis = 2 for rnn

X, Y, n_features, n_size, n_steps, year_target, month_target = get_XY_fr_resolution(input_vec, output_vec, n_steps = 2, axis = 1, req_m_input = [1, 2], req_month = [4, 5, 6], yearlyyield = yearlyyield)

true
(24, 2)


In [339]:
print('X Shape')
print(X.shape)
print('Y Shape')
print(Y.shape)
print('n features')
print(n_features)
print('sample size')
print(n_size)

X Shape
(12, 3)
Y Shape
(12,)
n features
3
sample size
12


In [340]:
# print(X)

Seperate train set and test set for displaying

In [341]:
X_train, X_test, Y_train, Y_test =  train_test_split(X, Y, test_size=0.3)
X_train_ord = X[:int(n_size*(1-0.3)), :]
X_test_ord  = X[int(n_size*(1-0.3)):, :]
Y_train_ord = Y[:int(n_size*(1-0.3))]
Y_test_ord  = Y[int(n_size*(1-0.3)):]
print('train size')
print(X_train.shape)
print('test size')
print(X_test.shape)

train size
(8, 3)
test size
(4, 3)


<h1> Ridge Model w/o Normalization </h1>

In [313]:
# vector for record error
train_mae = np.array([])
test_mae = np.array([])

train_rmse = np.array([])
test_rmse = np.array([])

train_r2 = np.array([])
test_r2 = np.array([])

# using grid searchcv to optimize hyper param
reg_lr  = Ridge()
param   = {'alpha':[0.01, 0.001, 0.1, 0.5, 1, 5, 10, 100, 200, 300, 400, 1000, 10e4, 10e5]}
gsc     = GridSearchCV(reg_lr, param, cv = 3)
print(X.shape)
gsc.fit(X, np.log1p(Y))

reg_lr  = gsc.best_estimator_
print(gsc.best_estimator_)

(12, 3)
Ridge(alpha=200, copy_X=True, fit_intercept=True, max_iter=None,
   normalize=False, random_state=None, solver='auto', tol=0.001)


In [322]:
reg_lr.fit(X_train_ord, np.log1p(Y_train_ord))

Y_all_test = reg_lr.predict(X)
Y_all_test[Y_all_test<0] = 0

Y_all_test = np.expm1(Y_all_test)

train_mae = mae(Y[:int(n_size*(1-0.3))], Y_all_test[:int(n_size*(1-0.3))])
test_mae = mae(Y[int(n_size*(1-0.3)):], Y_all_test[int(n_size*(1-0.3)):])

train_rmse = rmse(Y[:int(n_size*(1-0.3))], Y_all_test[:int(n_size*(1-0.3))])
test_rmse = rmse(Y[int(n_size*(1-0.3)):], Y_all_test[int(n_size*(1-0.3)):])

train_mape = mape(Y[:int(n_size*(1-0.3))], Y_all_test[:int(n_size*(1-0.3))])
test_mape = mape(Y[int(n_size*(1-0.3)):], Y_all_test[int(n_size*(1-0.3)):])

print('train MAE {:.2f}\ttest MAE {:.2f}'.format(train_mae, test_mae))
print('train RMSE {:.2f}\ttest RMSE {:.2f}'.format(train_rmse, test_rmse))
print('train MAPE {:.2f}\ttest MAPE {:.2f}'.format(train_mape, test_mape))
print('=========================')

if yearlyyield == False:
    for year, month, y_true, y_pred in zip(year_target, month_target, Y, Y_all_test):
        print('year {:.0f} month {:.0f} true : {:.0f}\tpred : {:.0f}'.format(year, month, y_true, y_pred))
else:
    for year, y_true, y_pred in zip(year_target, Y, Y_all_test):
        print('year {:.0f} true : {:.0f}\tpred : {:.0f}'.format(year, y_true, y_pred))   

train MAE 5501.66	test MAE 2387.15
train RMSE 6274.74	test RMSE 2958.93
train MAPE 25.60	test MAPE 10.63
year 2007 true : 23229	pred : 22037
year 2008 true : 19089	pred : 22102
year 2009 true : 27922	pred : 22389
year 2010 true : 16052	pred : 22641
year 2011 true : 14033	pred : 22761
year 2012 true : 30097	pred : 22939
year 2013 true : 24997	pred : 23184
year 2014 true : 33525	pred : 23537
year 2015 true : 27016	pred : 23470
year 2016 true : 19180	pred : 23673
year 2017 true : 25349	pred : 23846
year 2018 true : 24130	pred : 24124


In [323]:
# export output
# X_rnn[:int(train_ratio*n_size), :, :]
year_train  = year_target[:int(n_size*(1-0.3))]
month_train = month_target[:int(n_size*(1-0.3))] if yearlyyield == False else year_train
year_test   = year_target[int(n_size*(1-0.3)):]
month_test  = month_target[int(n_size*(1-0.3)):] if yearlyyield == False else year_test
y_train_true = Y[:int(n_size*(1-0.3))]
y_train_pred = Y_all_test[:int(n_size*(1-0.3))]
y_test_true = Y[int(n_size*(1-0.3)):]
y_test_pred = Y_all_test[int(n_size*(1-0.3)):]
export_output('ridge_wonorm_results_monthly_input_yearly_output.xlsx', year_train, month_train, y_train_true, y_train_pred, year_test, month_test, y_test_true, y_test_pred)

<h1> Ridge Model w Normalization </h1>

In [311]:
# vector for record error
train_mae = np.array([])
test_mae = np.array([])

train_rmse = np.array([])
test_rmse = np.array([])

train_r2 = np.array([])
test_r2 = np.array([])

# using grid searchcv to optimize hyper param
estimators = [('normalize', MinMaxScaler()), ('lr', Ridge())]
pipe    = Pipeline(estimators)
param   = dict(lr__alpha=[0.01, 0.001, 0.1, 0.5, 1, 5, 10, 100, 10e3, 10e4])

gsc     = GridSearchCV(pipe, param, cv = 3)
gsc.fit(X, np.log1p(Y))

reg_lr_norm  = gsc.best_estimator_
print(gsc.best_estimator_)

Pipeline(memory=None,
     steps=[('normalize', MinMaxScaler(copy=True, feature_range=(0, 1))), ('lr', Ridge(alpha=10, copy_X=True, fit_intercept=True, max_iter=None,
   normalize=False, random_state=None, solver='auto', tol=0.001))])


In [312]:
reg_lr_norm.fit(X_train_ord, np.log1p(Y_train_ord))

Y_all_test = reg_lr_norm.predict(X)
Y_all_test[Y_all_test<0] = 0
Y_all_test = np.expm1(Y_all_test)

train_mae = mae(Y[:int(n_size*(1-0.3))], Y_all_test[:int(n_size*(1-0.3))])
test_mae = mae(Y[int(n_size*(1-0.3)):], Y_all_test[int(n_size*(1-0.3)):])

train_rmse = rmse(Y[:int(n_size*(1-0.3))], Y_all_test[:int(n_size*(1-0.3))])
test_rmse = rmse(Y[int(n_size*(1-0.3)):], Y_all_test[int(n_size*(1-0.3)):])

train_mape = mape(Y[:int(n_size*(1-0.3))], Y_all_test[:int(n_size*(1-0.3))])
test_mape = mape(Y[int(n_size*(1-0.3)):], Y_all_test[int(n_size*(1-0.3)):])

print('train MAE {:.2f}\ttest MAE {:.2f}'.format(train_mae, test_mae))
print('train RMSE {:.2f}\ttest RMSE {:.2f}'.format(train_rmse, test_rmse))
print('train MAPE {:.2f}\ttest MAPE {:.2f}'.format(train_mape, test_mape))
print('=========================')

if yearlyyield == False:
    for year, month, y_true, y_pred in zip(year_target, month_target, Y, Y_all_test):
        print('year {:.0f} month {:.0f} true : {:.0f}\tpred : {:.0f}'.format(year, month, y_true, y_pred))
else:
    for year, y_true, y_pred in zip(year_target, Y, Y_all_test):
        print('year {:.0f} true : {:.0f}\tpred : {:.0f}'.format(year, y_true, y_pred))   

train MAE 5544.55	test MAE 2742.87
train RMSE 6342.59	test RMSE 3052.73
train MAPE 25.75	test MAPE 11.84
year 2007 true : 23229	pred : 22353
year 2008 true : 19089	pred : 22243
year 2009 true : 27922	pred : 22519
year 2010 true : 16052	pred : 22702
year 2011 true : 14033	pred : 22719
year 2012 true : 30097	pred : 22770
year 2013 true : 24997	pred : 22954
year 2014 true : 33525	pred : 23308
year 2015 true : 27016	pred : 22946
year 2016 true : 19180	pred : 23062
year 2017 true : 25349	pred : 23105
year 2018 true : 24130	pred : 23355


<h1> Support Vector Regression w/o Normalization </h1>

In [315]:
# vector for record error
train_mae = np.array([])
test_mae = np.array([])

train_rmse = np.array([])
test_rmse = np.array([])

train_r2 = np.array([])
test_r2 = np.array([])

# using grid searchcv to optimize hyper param
estimators = [('svr', SVR(kernel = 'linear', gamma = 'scale'))]
pipe    = Pipeline(estimators)
param   = dict(
    svr__C=[0.001, 0.01, 0.1, 0.5, 1, 5, 100],
    svr__epsilon = [0.001, 0.01, 0.1, 0.5, 1])

gsc     = GridSearchCV(pipe, param, cv = 2)
# gsc.fit(X, np.log1p(Y))
gsc.fit(X, Y)

reg_svr  = gsc.best_estimator_
print(gsc.best_estimator_)

Pipeline(memory=None,
     steps=[('svr', SVR(C=0.001, cache_size=200, coef0=0.0, degree=3, epsilon=0.1, gamma='scale',
  kernel='linear', max_iter=-1, shrinking=True, tol=0.001, verbose=False))])


In [316]:
reg_svr.fit(X_train_ord, np.log1p(Y_train_ord))
# reg_svr.fit(X_train_ord, Y_train_ord)

Y_all_test = reg_svr.predict(X)
Y_all_test[Y_all_test<0] = 0
Y_all_test = np.expm1(Y_all_test)

train_mae = mae(Y[:int(n_size*(1-0.3))], Y_all_test[:int(n_size*(1-0.3))])
test_mae = mae(Y[int(n_size*(1-0.3)):], Y_all_test[int(n_size*(1-0.3)):])

train_rmse = rmse(Y[:int(n_size*(1-0.3))], Y_all_test[:int(n_size*(1-0.3))])
test_rmse = rmse(Y[int(n_size*(1-0.3)):], Y_all_test[int(n_size*(1-0.3)):])

train_mape = mape(Y[:int(n_size*(1-0.3))], Y_all_test[:int(n_size*(1-0.3))])
test_mape = mape(Y[int(n_size*(1-0.3)):], Y_all_test[int(n_size*(1-0.3)):])

print('train MAE {:.2f}\ttest MAE {:.2f}'.format(train_mae, test_mae))
print('train RMSE {:.2f}\ttest RMSE {:.2f}'.format(train_rmse, test_rmse))
print('train MAPE {:.2f}\ttest MAPE {:.2f}'.format(train_mape, test_mape))
print('=========================')

if yearlyyield == False:
    for year, month, y_true, y_pred in zip(year_target, month_target, Y, Y_all_test):
        print('year {:.0f} month {:.0f} true : {:.0f}\tpred : {:.0f}'.format(year, month, y_true, y_pred))
else:
    for year, y_true, y_pred in zip(year_target, Y, Y_all_test):
        print('year {:.0f} month {:.0f} true : {:.0f}\tpred : {:.0f}'.format(year, month, y_true, y_pred))   

train MAE 5259.46	test MAE 2383.46
train RMSE 6254.88	test RMSE 3051.81
train MAPE 25.83	test MAPE 11.00
year 2007 month 10 true : 23229	pred : 23276
year 2008 month 10 true : 19089	pred : 23329
year 2009 month 10 true : 27922	pred : 23591
year 2010 month 10 true : 16052	pred : 23750
year 2011 month 10 true : 14033	pred : 23945
year 2012 month 10 true : 30097	pred : 24035
year 2013 month 10 true : 24997	pred : 24235
year 2014 month 10 true : 33525	pred : 24503
year 2015 month 10 true : 27016	pred : 24397
year 2016 month 10 true : 19180	pred : 24587
year 2017 month 10 true : 25349	pred : 24697
year 2018 month 10 true : 24130	pred : 24986


<h1> Support Vector Regression w Normalization </h1>

In [342]:
# vector for record error
train_mae = np.array([])
test_mae = np.array([])

train_rmse = np.array([])
test_rmse = np.array([])

train_r2 = np.array([])
test_r2 = np.array([])

# using grid searchcv to optimize hyper param
estimators = [('normalize', MinMaxScaler()),('svr', SVR(kernel = 'linear', gamma = 'scale'))]
pipe    = Pipeline(estimators)
param   = dict(
    svr__C=[0.001, 0.01, 0.1, 0.5, 1, 5, 100],
    svr__epsilon = [0.001, 0.01, 0.1, 0.5, 1])

gsc     = GridSearchCV(pipe, param, cv = 2)
gsc.fit(X, np.log1p(Y))

reg_svr_norm  = gsc.best_estimator_
print(gsc.best_estimator_)

Pipeline(memory=None,
     steps=[('normalize', MinMaxScaler(copy=True, feature_range=(0, 1))), ('svr', SVR(C=0.001, cache_size=200, coef0=0.0, degree=3, epsilon=0.001,
  gamma='scale', kernel='linear', max_iter=-1, shrinking=True, tol=0.001,
  verbose=False))])


In [343]:
reg_svr_norm.fit(X_train_ord, np.log1p(Y_train_ord))

Y_all_test = reg_svr_norm.predict(X)
Y_all_test[Y_all_test<0] = 0
Y_all_test = np.expm1(Y_all_test)

train_mae = mae(Y[:int(n_size*(1-0.3))], Y_all_test[:int(n_size*(1-0.3))])
test_mae = mae(Y[int(n_size*(1-0.3)):], Y_all_test[int(n_size*(1-0.3)):])

train_rmse = rmse(Y[:int(n_size*(1-0.3))], Y_all_test[:int(n_size*(1-0.3))])
test_rmse = rmse(Y[int(n_size*(1-0.3)):], Y_all_test[int(n_size*(1-0.3)):])

train_mape = mape(Y[:int(n_size*(1-0.3))], Y_all_test[:int(n_size*(1-0.3))])
test_mape = mape(Y[int(n_size*(1-0.3)):], Y_all_test[int(n_size*(1-0.3)):])

print('train MAE {:.2f}\ttest MAE {:.2f}'.format(train_mae, test_mae))
print('train RMSE {:.2f}\ttest RMSE {:.2f}'.format(train_rmse, test_rmse))
print('train MAPE {:.2f}\t\ttest MAPE {:.2f}'.format(train_mape, test_mape))
print('=========================')

if yearlyyield == False:
    for year, month, y_true, y_pred in zip(year_target, month_target, Y, Y_all_test):
        print('year {:.0f} month {:.0f} true : {:.0f}\tpred : {:.0f}'.format(year, month, y_true, y_pred))
else:
    for year, y_true, y_pred in zip(year_target, Y, Y_all_test):
        print('year {:.0f} month {:.0f} true : {:.0f}\tpred : {:.0f}'.format(year, month, y_true, y_pred))   

train MAE 5501.98	test MAE 2275.03
train RMSE 6433.78	test RMSE 2932.88
train MAPE 27.09		test MAPE 10.37
year 2007 month 10 true : 23229	pred : 24069
year 2008 month 10 true : 19089	pred : 24066
year 2009 month 10 true : 27922	pred : 24090
year 2010 month 10 true : 16052	pred : 24093
year 2011 month 10 true : 14033	pred : 24118
year 2012 month 10 true : 30097	pred : 24112
year 2013 month 10 true : 24997	pred : 24124
year 2014 month 10 true : 33525	pred : 24142
year 2015 month 10 true : 27016	pred : 24115
year 2016 month 10 true : 19180	pred : 24130
year 2017 month 10 true : 25349	pred : 24128
year 2018 month 10 true : 24130	pred : 24159


In [344]:
# export output
year_train  = year_target[:int(n_size*(1-0.3))]
month_train = month_target[:int(n_size*(1-0.3))] if yearlyyield == False else year_train
year_test   = year_target[int(n_size*(1-0.3)):]
month_test  = month_target[int(n_size*(1-0.3)):] if yearlyyield == False else year_test
y_train_true = Y[:int(n_size*(1-0.3))]
y_train_pred = Y_all_test[:int(n_size*(1-0.3))]
y_test_true = Y[int(n_size*(1-0.3)):]
y_test_pred = Y_all_test[int(n_size*(1-0.3)):]
export_output('svr_wnorm_results_monthly_input_yearly_output_v3.xlsx', year_train, month_train, y_train_true, y_train_pred, year_test, month_test, y_test_true, y_test_pred)

<h1>Get X and y for Recurrent Neural Network</h1>

method for getting x data for rnn

In [324]:
choose = 'monthly_yearlyyield'

if choose == 'monthly_yearlyyield_wyear':
    yearlyyield = True
    input_vec = [
        [monthly_temp, 'x'],
        # [monthly_humid, 'x'], 
        # [monthly_rain, 'x'], 
        # [monthly_area, 'x'], 
        # [monthly_yieldarea, 'x'], 
        # [monthly_lychee, 'x'],
        [monthly_yieldarea[:,0].reshape(-1,1), 'y']]   # target year

    output_vec = [monthly_lychee_yearlyyield]

if choose == 'monthly_yearlyyield_woyear':
    yearlyyield = True
    input_vec = [
        [monthly_temp, 'x'],
        # [monthly_humid, 'x'], 
        # [monthly_rain, 'x'], 
        # [monthly_area, 'x'], 
        # [monthly_yieldarea, 'x'], 
        # [monthly_lychee, 'x'],
        ]#[monthly_yieldarea[:,0].reshape(-1,1), 'y']]   # target year
        
if choose == 'test':
    input_vec = [
        [daily_temp, 'x'], 
        [daily_yieldarea[:,0].reshape(-1,1), 'y'],   # target year
        [daily_yieldarea[:,0:2].reshape(-1,2), 'y']] # target month

    output_vec = [daily_lychee]

if choose == 'monthly':
    yearlyyield = False
    input_vec = [
        [monthly_temp, 'x'],
        # [monthly_humid, 'x'], 
        # [monthly_rain, 'x'], 
        # [monthly_area, 'x'], 
        [monthly_yieldarea, 'x'], 
        [monthly_lychee, 'x'], 
        [monthly_yieldarea[:,0].reshape(-1,1), 'y'],   # target year
        [monthly_yieldarea[:,0:2].reshape(-1,2), 'y']] # target month
    
    output_vec = [monthly_lychee]

if choose == 'daily':
    yearlyyield = False
    input_vec = [
        [daily_temp, 'x'],
        [daily_humid, 'x'], 
        # [daily_rain, 'x'], 
        # [daily_area, 'x'], 
        # [daily_yieldarea, 'x'], 
        [daily_lychee, 'x'], 
        [daily_yieldarea[:,0].reshape(-1,1), 'y'],   # target year
        [daily_yieldarea[:,0:2].reshape(-1,2), 'y']] # target month

    output_vec = [daily_lychee]

if choose == 'hourly':
    yearlyyield = False
    input_vec = [
        [hourly_temp, 'x'],
        # [hourly_humid, 'x'], 
        # [hourly_rain, 'x'], 
        # [hourly_area, 'x'], 
        [hourly_yieldarea, 'x'], 
        [hourly_lychee, 'x'], 
        [hourly_yieldarea[:,0].reshape(-1,1), 'y'],   # target year
        [hourly_yieldarea[:,0:2].reshape(-1,2), 'y']] # target month

    output_vec = [hourly_lychee]

# daily choose n_steps = 240
# hourly choose n_steps = 1920
# monthly choose n_steps = 4
# axis = 2 for rnn

########## choose architecture of neural network

choose = 'gru'

X_rnn, Y_rnn, n_features, n_size, n_steps, year_target, month_target = get_XY_fr_resolution(input_vec, output_vec, n_steps = 2, axis = 1 if choose == 'ann' else 2, req_m_input = [1, 2], req_month = [4, 5, 6], yearlyyield = yearlyyield)

print('n_steps : {:d} n_features : {:d} n_size : {:d}'.format(n_steps, n_features, n_size))

true
(24, 2)
n_steps : 2 n_features : 2 n_size : 12


Seperate train set and test set with unshuffle for displaying</br>
test size = 53
train size = 124

In [325]:
train_ratio = 0.7

X_train_ord         = X_rnn[:int(train_ratio*n_size), :] if choose == 'ann' else X_rnn[:int(train_ratio*n_size), :, :]
X_test_ord          = X_rnn[int(train_ratio*n_size):, :] if choose == 'ann' else X_rnn[int(train_ratio*n_size):, :, :]
Y_train_ord         = Y_rnn[:int(train_ratio*n_size)].reshape(-1)
Y_test_ord          = Y_rnn[int(train_ratio*n_size):].reshape(-1)
print(Y_train_ord.shape)

(8,)


In [326]:
X_train     = X_train_ord
X_test      = X_test_ord
Y_train     = Y_train_ord
Y_test      = Y_test_ord

print(X_train.shape)
print(Y_train.shape)

(8, 2, 2)
(8,)


<h1> Recurrent Neural Network w/o Normalization </h1>

In [327]:
class Scaler3D():

    def __init__(self):
        self.scaler_list = {}

    def fit(self, x):
        self.x = x
        
        min_list = np.array([])
        max_list = np.array([])

        len_feature = x.shape[-1]

        for i in range(len_feature):
            self.scaler_list[i] = MinMaxScaler()
            self.scaler_list[i].fit(x[:, :, i])

    def transform(self, x):
        x_copy = x.copy()

        len_feature = x.shape[-1]

        for i in range(len_feature):
            x_copy[:,:,i] = self.scaler_list[i].transform(x[:, :, i])

        return x_copy

In [328]:
def create_model_lstm(n_steps, n_features):
    rnn = Sequential()
    rnn.add(LSTM(10, activation='relu', return_sequences=True, input_shape=(n_steps, n_features)))
    rnn.add(Dropout(0.2))
    rnn.add(LSTM(50, activation='relu'))
    rnn.add(Dropout(0.2))
    rnn.add(Dense(50, activation='relu'))
    rnn.add(Dropout(0.2))
    rnn.add(Dense(1, activation='relu'))
    rnn.compile(optimizer='adam', loss='mse')

    return rnn  

In [329]:
def create_model_gru(n_steps, n_features):
    
    rnn = Sequential()
    rnn.add(GRU(100, activation='relu', return_sequences=True, input_shape=(n_steps, n_features)))
    rnn.add(Dropout(0.4))
    rnn.add(GRU(100, activation='relu', return_sequences=True))
    rnn.add(Dropout(0.4))
    rnn.add(GRU(100, activation='relu'))    
    # rnn.add(BatchNormalization())    
    rnn.add(Dropout(0.4))
    rnn.add(Dense(50, activation='relu'))
    rnn.add(Dropout(0.4))    
    rnn.add(Dense(1, activation='relu'))
    rnn.compile(optimizer='adam', loss='mse')
    return rnn  

In [330]:
def create_model_ann(n_steps, n_features):
    reg = l1(0.01)
    rnn = Sequential()
    # input layer
    rnn.add(Dense(128, activation='relu', input_dim=n_features))
    # hidden layer
    rnn.add(Dense(256, activation='relu',
                kernel_regularizer=reg)) 
    rnn.add(Dropout(0.4))
    rnn.add(Dense(256, activation='relu',
                kernel_regularizer=reg))   
    rnn.add(Dropout(0.4)) 
    rnn.add(Dense(256, activation='relu',
                kernel_regularizer=reg))   
    rnn.add(Dropout(0.4))     
    # output layer
    rnn.add(Dense(1, activation='relu'))
    rnn.compile(optimizer='adam', loss='mse')
    return rnn  

<h1> Recurrent Neural Network w Normalization </h1>

In [333]:
# Create a callback that saves the model's weights
if choose == 'lstm':
    checkpoint_path = './checkpoint_path_lstm'
    rnn = create_model_lstm(n_steps, n_features)   
elif choose == 'gru':
    checkpoint_path = './checkpoint_path_gru_3layer_monthly_yearlyyield.ckpt'
    rnn = create_model_gru(n_steps, n_features)   
else:
    checkpoint_path = './checkpoint_path_ann_3layer_monthly_yearlyyield.ckpt'
    rnn = create_model_ann(n_steps, n_features)       

cp_callback     = tensorflow.keras.callbacks.ModelCheckpoint(filepath=checkpoint_path,
                                                 save_weights_only=True,
                                                 verbose=0)        
rnn.summary()        

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
gru_3 (GRU)                  (None, 2, 100)            31200     
_________________________________________________________________
dropout_4 (Dropout)          (None, 2, 100)            0         
_________________________________________________________________
gru_4 (GRU)                  (None, 2, 100)            60600     
_________________________________________________________________
dropout_5 (Dropout)          (None, 2, 100)            0         
_________________________________________________________________
gru_5 (GRU)                  (None, 100)               60600     
_________________________________________________________________
dropout_6 (Dropout)          (None, 100)               0         
_________________________________________________________________
dense_2 (Dense)              (None, 50)               

In [334]:
# vector for record error
train_mae = np.array([])
test_mae = np.array([])

train_rmse = np.array([])
test_rmse = np.array([])

train_r2 = np.array([])
test_r2 = np.array([])

# minmaxscaler
scaler = Scaler3D()
scaler.fit(X_train)

for i in range(300):

    # if os.path.isfile(checkpoint_path):
    #     rnn.load_weights(checkpoint_path)

        if choose != 'ann':
            rnn.fit(scaler.transform(X_train), np.log1p(Y_train), epochs=50, verbose=0, batch_size=32)#, callbacks=[cp_callback])

            Y_test_pred = rnn.predict(scaler.transform(X_test))
            Y_test_pred[Y_test_pred<0] = 0

            Y_train_pred = rnn.predict(scaler.transform(X_train))
            Y_train_pred[Y_train_pred<0] = 0

            Y_test_pred = np.expm1(Y_test_pred)
            Y_train_pred = np.expm1(Y_train_pred)

        else:
            rnn.fit(scaler.transform(X_train), np.log1p(Y_train), epochs=1, verbose=1, batch_size=32)#, callbacks=[cp_callback])

            Y_test_pred = rnn.predict(X_test)
            Y_test_pred[Y_test_pred<0] = 0

            Y_train_pred = rnn.predict(X_train)
            Y_train_pred[Y_train_pred<0] = 0

            Y_test_pred = np.expm1(Y_test_pred)
            Y_train_pred = np.expm1(Y_train_pred)

            Y_train = np.expm1(Y_train)
            Y_test  = np.expm1(Y_test)

        train_mae = np.append(train_mae, mae(Y_train, Y_train_pred))
        test_mae = np.append(test_mae, mae(Y_test, Y_test_pred))

        train_rmse = np.append(train_rmse, rmse(Y_train, Y_train_pred))
        test_rmse = np.append(test_rmse, rmse(Y_test, Y_test_pred)) 

        if i%10 == 0:
            print('---- Iter : {:d} ----'.format(i))

            print('Train set MAE {:.2f}'.format(np.mean(train_mae[-1])))
            print('Test set MAE {:.2f}'.format(np.mean(test_mae[-1])))

            print('Train set RMSE {:.2f}'.format(np.mean(train_rmse[-1])))
            print('Test set RMSE {:.2f}'.format(np.mean(test_rmse[-1])))  

---- Iter : 0 ----
Train set MAE 18541.28
Test set MAE 110318.82
Train set RMSE 20354.44
Test set RMSE 188651.83
---- Iter : 10 ----
Train set MAE 11817.31
Test set MAE 5166.91
Train set RMSE 13514.30
Test set RMSE 6714.18
---- Iter : 20 ----
Train set MAE 6625.75
Test set MAE 7778.90
Train set RMSE 7885.79
Test set RMSE 8622.17
---- Iter : 30 ----
Train set MAE 12373.87
Test set MAE 30452.94
Train set RMSE 14221.28
Test set RMSE 30777.44
---- Iter : 40 ----
Train set MAE 8330.13
Test set MAE 4432.80
Train set RMSE 10151.57
Test set RMSE 5085.23
---- Iter : 50 ----
Train set MAE 9125.39
Test set MAE 5840.25
Train set RMSE 10999.74
Test set RMSE 6567.85
---- Iter : 60 ----
Train set MAE 9432.55
Test set MAE 7214.61
Train set RMSE 11290.72
Test set RMSE 7973.55
---- Iter : 70 ----
Train set MAE 6242.79
Test set MAE 4282.46
Train set RMSE 7460.30
Test set RMSE 5540.87
---- Iter : 80 ----
Train set MAE 7901.04
Test set MAE 6182.50
Train set RMSE 9574.21
Test set RMSE 7235.92
---- Iter : 90

In [335]:
Y_all_test = rnn.predict(scaler.transform(X_rnn))
Y_all_test[Y_all_test<0] = 0

Y_all_test = np.expm1(Y_all_test)
# Y_all_test = scaler_Y.inverse_transform(Y_all_test)

train_mae = mae(Y_rnn[:int(n_size*(1-0.3))], Y_all_test[:int(n_size*(1-0.3))])
test_mae = mae(Y_rnn[int(n_size*(1-0.3)):], Y_all_test[int(n_size*(1-0.3)):])

train_rmse = rmse(Y_rnn[:int(n_size*(1-0.3))], Y_all_test[:int(n_size*(1-0.3))])
test_rmse = rmse(Y_rnn[int(n_size*(1-0.3)):], Y_all_test[int(n_size*(1-0.3)):])

train_mape = mape(Y[:int(n_size*(1-0.3))], Y_all_test[:int(n_size*(1-0.3))])
test_mape = mape(Y[int(n_size*(1-0.3)):], Y_all_test[int(n_size*(1-0.3)):])

print('train MAE {:.2f}\ttest MAE {:.2f}'.format(train_mae, test_mae))
print('train RMSE {:.2f}\ttest RMSE {:.2f}'.format(train_rmse, test_rmse))
print('train MAPE {:.2f}\t\ttest MAPE {:.2f}'.format(train_mape, test_mape))
print('=========================')

if yearlyyield == False:
    for year, month, y_true, y_pred in zip(year_target, month_target, Y, Y_all_test):
        print('year {:.0f} month {:.0f} true : {:.0f}\tpred : {:.0f}'.format(year, month, y_true, y_pred))
else:
    for year, y_true, y_pred in zip(year_target, Y, Y_all_test):
        print('year {:.0f} true : {:.0f}\tpred : {:.0f}'.format(year, y_true, y_pred[0]))   

train MAE 2518.34	test MAE 4483.59
train RMSE 3107.60	test RMSE 5374.50
train MAPE 29.39		test MAPE 17.09
year 2007 true : 23229	pred : 20032
year 2008 true : 19089	pred : 17590
year 2009 true : 27922	pred : 25463
year 2010 true : 16052	pred : 16916
year 2011 true : 14033	pred : 15299
year 2012 true : 30097	pred : 25137
year 2013 true : 24997	pred : 25266
year 2014 true : 33525	pred : 27893
year 2015 true : 27016	pred : 18358
year 2016 true : 19180	pred : 20686
year 2017 true : 25349	pred : 19448
year 2018 true : 24130	pred : 26000


In [336]:
# export output
# X_rnn[:int(train_ratio*n_size), :, :]
year_train  = year_target[:int(n_size*(1-0.3))]
month_train = month_target[:int(n_size*(1-0.3))] if yearlyyield == False else year_train
year_test   = year_target[int(n_size*(1-0.3)):]
month_test  = month_target[int(n_size*(1-0.3)):] if yearlyyield == False else year_test
y_train_true = Y[:int(n_size*(1-0.3))]
y_train_pred = Y_all_test[:int(n_size*(1-0.3))]
y_test_true = Y[int(n_size*(1-0.3)):]
y_test_pred = Y_all_test[int(n_size*(1-0.3)):]
export_output('rnn_wnorm_results_monthly_input_yearly_output.xlsx', year_train, month_train, y_train_true, y_train_pred, year_test, month_test, y_test_true, y_test_pred)